require('dotenv').config()
const mongoose     = require('mongoose')
const collegeModel = require('./models/collegemodels')
const festModel    = require('./models/festmodels')
const upcomingModel= require('./models/upcomingmodels')
const contactModel= require('./models/contactmodels')

const COLLEGES = [
  { id:'dtu',      name:'Delhi Technological University',         short:'DTU',   type:'state', typeName:'State Univ.', location:'Rohini, Delhi',       color:'#6c63ff', glow:'rgba(108,99,255,0.12)',  fests:14, sponsors:85,  years:5, established:1941, students:'10,000+', fesTypes:['cultural','tech','sports'] },
  { id:'nsut',     name:'Netaji Subhas University of Technology', short:'NSUT',  type:'state', typeName:'State Univ.', location:'Dwarka, Delhi',        color:'#ff6584', glow:'rgba(255,101,132,0.12)', fests:10, sponsors:62,  years:4, established:1983, students:'7,500+',  fesTypes:['cultural','tech','sports'] },
  { id:'iitd',     name:'IIT Delhi',                              short:'IITD',  type:'iit',   typeName:'IIT',         location:'Hauz Khas, Delhi',      color:'#43e8c0', glow:'rgba(67,232,192,0.12)',  fests:18, sponsors:130, years:5, established:1961, students:'8,500+',  fesTypes:['cultural','tech','sports'] },
  { id:'iiitd',    name:'IIIT Delhi',                             short:'IIITD', type:'iiit',  typeName:'IIIT',         location:'Okhla, Delhi',          color:'#ffb74d', glow:'rgba(255,183,77,0.12)',  fests:8,  sponsors:44,  years:4, established:2008, students:'3,000+',  fesTypes:['cultural','tech'] },
  { id:'srcc',     name:'Shri Ram College of Commerce',           short:'SRCC',  type:'du',    typeName:'DU College',  location:'North Campus, Delhi',   color:'#ff6584', glow:'rgba(255,101,132,0.12)', fests:6,  sponsors:48,  years:5, established:1926, students:'2,500+',  fesTypes:['cultural','other'] },
  { id:'stephens', name:"St. Stephen's College",                  short:'STC',   type:'du',    typeName:'DU College',  location:'North Campus, Delhi',   color:'#64dc64', glow:'rgba(100,220,100,0.12)', fests:5,  sponsors:32,  years:4, established:1881, students:'2,000+',  fesTypes:['cultural','sports'] },
  { id:'iitb',     name:'IIT Bombay',                             short:'IITB',  type:'iit',   typeName:'IIT',         location:'Powai, Mumbai',          color:'#43e8c0', glow:'rgba(67,232,192,0.12)',  fests:20, sponsors:160, years:5, established:1958, students:'11,000+', fesTypes:['cultural','tech','sports'] },
  { id:'iitk',     name:'IIT Kanpur',                             short:'IITK',  type:'iit',   typeName:'IIT',         location:'Kanpur, UP',             color:'#43e8c0', glow:'rgba(67,232,192,0.12)',  fests:16, sponsors:110, years:5, established:1959, students:'9,000+',  fesTypes:['cultural','tech','sports'] },
  { id:'lsr',      name:'Lady Shri Ram College',                  short:'LSR',   type:'du',    typeName:'DU College',  location:'Lajpat Nagar, Delhi',   color:'#ff6584', glow:'rgba(255,101,132,0.12)', fests:7,  sponsors:40,  years:4, established:1956, students:'2,800+',  fesTypes:['cultural','sports'] },
]

const FESTS = [
  { id:'engifest',      collegeId:'dtu',      name:'Engifest',      tagline:"DTU's flagship cultural & technical fest",                type:'cultural', icon:'🎭', iconBg:'rgba(108,99,255,0.15)',  footfall:'50,000+',   sponsors_count:30, years:{ '2024':[{name:'Reliance Jio',tier:'title',category:'Telecom'},{name:'Coca-Cola',tier:'gold',category:'Beverage'},{name:'Nykaa',tier:'gold',category:'Beauty'},{name:'Amazon',tier:'silver',category:'E-commerce'},{name:'boAt',tier:'silver',category:'Electronics'},{name:'Swiggy',tier:'partner',category:'Food Delivery'},{name:'Razorpay',tier:'associate',category:'Fintech'},{name:'HDFC Bank',tier:'silver',category:'Banking'},{name:'Fastrack',tier:'bronze',category:'Fashion'}],'2023':[{name:'Airtel',tier:'title',category:'Telecom'},{name:'Paytm',tier:'gold',category:'Fintech'},{name:'Zomato',tier:'gold',category:'Food Delivery'},{name:'Samsung',tier:'silver',category:'Electronics'},{name:'Ola',tier:'silver',category:'Mobility'},{name:'Puma',tier:'bronze',category:'Sportswear'},{name:'Spotify',tier:'partner',category:'Music Streaming'}],'2022':[{name:'Dream11',tier:'title',category:'Fantasy Sports'},{name:'Jio',tier:'gold',category:'Telecom'},{name:"BYJU'S",tier:'silver',category:'EdTech'},{name:'RedBull',tier:'partner',category:'Beverages'}],'2021':[{name:"BYJU'S",tier:'title',category:'EdTech'},{name:'Unacademy',tier:'gold',category:'EdTech'},{name:'Flipkart',tier:'silver',category:'E-commerce'}],'2020':[{name:'Paytm',tier:'title',category:'Fintech'},{name:'Amazon',tier:'gold',category:'E-commerce'},{name:'Swiggy',tier:'silver',category:'Food Delivery'}] } },
  { id:'tryst_dtu',     collegeId:'dtu',      name:'Tryst',         tagline:"DTU's annual technical festival",                         type:'tech',     icon:'⚙️', iconBg:'rgba(67,232,192,0.12)',   footfall:'20,000+',   sponsors_count:18, years:{ '2024':[{name:'Google',tier:'title',category:'Technology'},{name:'Microsoft',tier:'gold',category:'Technology'},{name:'Flipkart',tier:'gold',category:'E-commerce'},{name:'Razorpay',tier:'silver',category:'Fintech'},{name:'GitHub',tier:'partner',category:'Dev Tools'}],'2023':[{name:'Amazon',tier:'title',category:'Technology'},{name:'Flipkart',tier:'gold',category:'E-commerce'},{name:'Postman',tier:'silver',category:'Dev Tools'}],'2022':[{name:'Infosys',tier:'title',category:'IT Services'},{name:'Wipro',tier:'gold',category:'IT Services'}] } },
  { id:'spardha',       collegeId:'dtu',      name:'Spardha',       tagline:"DTU's annual sports meet",                                type:'sports',   icon:'🏆', iconBg:'rgba(255,183,77,0.12)',   footfall:'8,000+',    sponsors_count:10, years:{ '2024':[{name:'Decathlon',tier:'title',category:'Sporting Goods'},{name:'Puma',tier:'gold',category:'Sportswear'},{name:'Gatorade',tier:'silver',category:'Beverages'},{name:'Nike',tier:'bronze',category:'Sportswear'}],'2023':[{name:'Adidas',tier:'title',category:'Sportswear'},{name:'Decathlon',tier:'gold',category:'Sporting Goods'}] } },
  { id:'moksha',        collegeId:'nsut',     name:'Moksha',        tagline:"NSUT's flagship annual cultural festival",                type:'cultural', icon:'🎭', iconBg:'rgba(255,101,132,0.15)',  footfall:'50,000+',   sponsors_count:22, years:{ '2024':[{name:'Pepsi',tier:'title',category:'Beverages'},{name:'Flipkart',tier:'gold',category:'E-commerce'},{name:'boAt',tier:'gold',category:'Electronics'},{name:'Swiggy',tier:'silver',category:'Food Delivery'},{name:'PhonePe',tier:'partner',category:'Fintech'}],'2023':[{name:'Jio',tier:'title',category:'Telecom'},{name:'Zomato',tier:'gold',category:'Food Delivery'},{name:'Amazon',tier:'gold',category:'E-commerce'},{name:'HDFC Bank',tier:'silver',category:'Banking'}],'2022':[{name:'Airtel',tier:'title',category:'Telecom'},{name:'Paytm',tier:'gold',category:'Fintech'},{name:'MakeMyTrip',tier:'silver',category:'Travel'}],'2021':[{name:"BYJU'S",tier:'title',category:'EdTech'},{name:'Unacademy',tier:'gold',category:'EdTech'}] } },
  { id:'ojas',          collegeId:'nsut',     name:'Ojas',          tagline:"NSUT's annual technical symposium",                       type:'tech',     icon:'⚙️', iconBg:'rgba(67,232,192,0.12)',   footfall:'12,000+',   sponsors_count:14, years:{ '2024':[{name:'Microsoft',tier:'title',category:'Technology'},{name:'IBM',tier:'gold',category:'IT Services'},{name:'Razorpay',tier:'silver',category:'Fintech'},{name:'GitHub',tier:'partner',category:'Dev Tools'}],'2023':[{name:'Google',tier:'title',category:'Technology'},{name:'Infosys',tier:'gold',category:'IT Services'}] } },
  { id:'rendezvous',    collegeId:'iitd',     name:'Rendezvous',    tagline:"IIT Delhi's flagship cultural festival",                  type:'cultural', icon:'🎭', iconBg:'rgba(67,232,192,0.15)',   footfall:'60,000+',   sponsors_count:35, years:{ '2024':[{name:'HDFC Bank',tier:'title',category:'Banking'},{name:'Coca-Cola',tier:'gold',category:'Beverages'},{name:'Myntra',tier:'gold',category:'Fashion'},{name:'boAt',tier:'silver',category:'Electronics'},{name:'Swiggy',tier:'silver',category:'Food Delivery'},{name:'Spotify',tier:'partner',category:'Music Streaming'}],'2023':[{name:'Jio',tier:'title',category:'Telecom'},{name:'Amazon',tier:'gold',category:'E-commerce'},{name:'Nykaa',tier:'gold',category:'Beauty'},{name:'Dream11',tier:'silver',category:'Fantasy Sports'}],'2022':[{name:'Airtel',tier:'title',category:'Telecom'},{name:'Flipkart',tier:'gold',category:'E-commerce'},{name:'Puma',tier:'silver',category:'Sportswear'}],'2021':[{name:"BYJU'S",tier:'title',category:'EdTech'},{name:'Paytm',tier:'gold',category:'Fintech'}],'2020':[{name:'Pepsi',tier:'title',category:'Beverages'},{name:'Amazon',tier:'gold',category:'E-commerce'}] } },
  { id:'tryst_iitd',    collegeId:'iitd',     name:'Tryst',         tagline:"IIT Delhi's premier technical festival",                  type:'tech',     icon:'⚙️', iconBg:'rgba(67,232,192,0.12)',   footfall:'30,000+',   sponsors_count:25, years:{ '2024':[{name:'Google',tier:'title',category:'Technology'},{name:'Microsoft',tier:'gold',category:'Technology'},{name:'Adobe',tier:'gold',category:'Software'},{name:'Goldman Sachs',tier:'silver',category:'Finance'}],'2023':[{name:'Amazon',tier:'title',category:'Technology'},{name:'Flipkart',tier:'gold',category:'E-commerce'},{name:'Atlassian',tier:'silver',category:'Dev Tools'}] } },
  { id:'odyssey',       collegeId:'iiitd',    name:'Odyssey',       tagline:"IIIT Delhi's growing cultural extravaganza",              type:'cultural', icon:'🎭', iconBg:'rgba(255,183,77,0.15)',   footfall:'15,000+',   sponsors_count:16, years:{ '2024':[{name:'Airtel',tier:'title',category:'Telecom'},{name:'Zomato',tier:'gold',category:'Food Delivery'},{name:'boAt',tier:'gold',category:'Electronics'},{name:'Swiggy',tier:'silver',category:'Food Delivery'},{name:'Cred',tier:'partner',category:'Fintech'}],'2023':[{name:'Pepsi',tier:'title',category:'Beverages'},{name:'Myntra',tier:'gold',category:'Fashion'},{name:'PhonePe',tier:'silver',category:'Fintech'}],'2022':[{name:'Jio',tier:'title',category:'Telecom'},{name:'Amazon',tier:'gold',category:'E-commerce'}] } },
  { id:'esya',          collegeId:'iiitd',    name:'Esya',          tagline:"IIIT Delhi's flagship technical festival",                type:'tech',     icon:'⚙️', iconBg:'rgba(67,232,192,0.12)',   footfall:'10,000+',   sponsors_count:14, years:{ '2024':[{name:'Microsoft',tier:'title',category:'Technology'},{name:'Google',tier:'gold',category:'Technology'},{name:'Razorpay',tier:'silver',category:'Fintech'},{name:'GitHub',tier:'partner',category:'Dev Tools'}],'2023':[{name:'Amazon',tier:'title',category:'Technology'},{name:'IBM',tier:'gold',category:'IT Services'}] } },
  { id:'crossroads',    collegeId:'srcc',     name:'Crossroads',    tagline:"SRCC's iconic annual cultural festival",                  type:'cultural', icon:'🎭', iconBg:'rgba(255,101,132,0.15)',  footfall:'20,000+',   sponsors_count:20, years:{ '2024':[{name:'Audi',tier:'title',category:'Automobile'},{name:'Pepsi',tier:'gold',category:'Beverages'},{name:'HDFC Bank',tier:'silver',category:'Banking'},{name:'Myntra',tier:'silver',category:'Fashion'},{name:'Zomato',tier:'partner',category:'Food Delivery'}],'2023':[{name:'BMW',tier:'title',category:'Automobile'},{name:'Coca-Cola',tier:'gold',category:'Beverages'},{name:'Flipkart',tier:'gold',category:'E-commerce'},{name:'boAt',tier:'silver',category:'Electronics'}],'2022':[{name:'Mercedes',tier:'title',category:'Automobile'},{name:'Pepsi',tier:'gold',category:'Beverages'},{name:'Nykaa',tier:'silver',category:'Beauty'}],'2021':[{name:'Jio',tier:'title',category:'Telecom'},{name:'Amazon',tier:'gold',category:'E-commerce'}],'2020':[{name:'HDFC Bank',tier:'title',category:'Banking'},{name:'Pepsi',tier:'gold',category:'Beverages'}] } },
  { id:'interface',     collegeId:'srcc',     name:'Interface',     tagline:"SRCC's commerce & entrepreneurship conclave",             type:'other',    icon:'💼', iconBg:'rgba(255,183,77,0.12)',   footfall:'5,000+',    sponsors_count:12, years:{ '2024':[{name:'Deloitte',tier:'title',category:'Consulting'},{name:'EY',tier:'gold',category:'Consulting'},{name:'KPMG',tier:'silver',category:'Consulting'}],'2023':[{name:'PwC',tier:'title',category:'Consulting'},{name:'Goldman Sachs',tier:'gold',category:'Finance'}] } },
  { id:'stephania',     collegeId:'stephens', name:'Stephania',     tagline:"St. Stephen's prestigious annual cultural festival",      type:'cultural', icon:'🎭', iconBg:'rgba(100,220,100,0.15)',  footfall:'10,000+',   sponsors_count:14, years:{ '2024':[{name:'Pepsi',tier:'title',category:'Beverages'},{name:'HDFC Bank',tier:'gold',category:'Banking'},{name:'Myntra',tier:'silver',category:'Fashion'},{name:'Spotify',tier:'partner',category:'Music Streaming'}],'2023':[{name:'Coca-Cola',tier:'title',category:'Beverages'},{name:'Flipkart',tier:'gold',category:'E-commerce'},{name:'boAt',tier:'silver',category:'Electronics'}],'2022':[{name:'Jio',tier:'title',category:'Telecom'},{name:'Amazon',tier:'gold',category:'E-commerce'}],'2021':[{name:'Airtel',tier:'title',category:'Telecom'},{name:'Paytm',tier:'gold',category:'Fintech'}] } },
  { id:'moodindigo',    collegeId:'iitb',     name:'Mood Indigo',   tagline:"Asia's largest college cultural festival",                type:'cultural', icon:'🎭', iconBg:'rgba(67,232,192,0.15)',   footfall:'1,50,000+', sponsors_count:50, years:{ '2024':[{name:'Jio',tier:'title',category:'Telecom'},{name:'Coca-Cola',tier:'gold',category:'Beverages'},{name:'Amazon',tier:'gold',category:'E-commerce'},{name:'Myntra',tier:'silver',category:'Fashion'},{name:'boAt',tier:'silver',category:'Electronics'},{name:'Swiggy',tier:'partner',category:'Food Delivery'},{name:'Spotify',tier:'partner',category:'Music Streaming'}],'2023':[{name:'Airtel',tier:'title',category:'Telecom'},{name:'Flipkart',tier:'gold',category:'E-commerce'},{name:'Pepsi',tier:'gold',category:'Beverages'},{name:'Dream11',tier:'silver',category:'Fantasy Sports'}],'2022':[{name:'HDFC Bank',tier:'title',category:'Banking'},{name:'Coca-Cola',tier:'gold',category:'Beverages'},{name:'Ola',tier:'silver',category:'Mobility'}],'2021':[{name:"BYJU'S",tier:'title',category:'EdTech'},{name:'Amazon',tier:'gold',category:'E-commerce'}],'2020':[{name:'Jio',tier:'title',category:'Telecom'},{name:'Pepsi',tier:'gold',category:'Beverages'}] } },
  { id:'techfest',      collegeId:'iitb',     name:'Techfest',      tagline:"Asia's largest science & technology festival",            type:'tech',     icon:'⚙️', iconBg:'rgba(67,232,192,0.12)',   footfall:'1,80,000+', sponsors_count:45, years:{ '2024':[{name:'Google',tier:'title',category:'Technology'},{name:'Microsoft',tier:'gold',category:'Technology'},{name:'Samsung',tier:'gold',category:'Electronics'},{name:'Goldman Sachs',tier:'silver',category:'Finance'},{name:'Adobe',tier:'silver',category:'Software'}],'2023':[{name:'Amazon',tier:'title',category:'Technology'},{name:'Qualcomm',tier:'gold',category:'Semiconductors'},{name:'Flipkart',tier:'silver',category:'E-commerce'}] } },
  { id:'antaragni',     collegeId:'iitk',     name:'Antaragni',     tagline:"IIT Kanpur's iconic cultural festival since 1965",        type:'cultural', icon:'🎭', iconBg:'rgba(67,232,192,0.15)',   footfall:'80,000+',   sponsors_count:35, years:{ '2024':[{name:'Pepsi',tier:'title',category:'Beverages'},{name:'Jio',tier:'gold',category:'Telecom'},{name:'Amazon',tier:'gold',category:'E-commerce'},{name:'boAt',tier:'silver',category:'Electronics'},{name:'Swiggy',tier:'silver',category:'Food Delivery'},{name:'PhonePe',tier:'partner',category:'Fintech'}],'2023':[{name:'Airtel',tier:'title',category:'Telecom'},{name:'Coca-Cola',tier:'gold',category:'Beverages'},{name:'Flipkart',tier:'gold',category:'E-commerce'},{name:'Ola',tier:'silver',category:'Mobility'}],'2022':[{name:'Dream11',tier:'title',category:'Fantasy Sports'},{name:'HDFC Bank',tier:'gold',category:'Banking'},{name:'Myntra',tier:'silver',category:'Fashion'}],'2021':[{name:"BYJU'S",tier:'title',category:'EdTech'},{name:'Unacademy',tier:'gold',category:'EdTech'}],'2020':[{name:'Jio',tier:'title',category:'Telecom'},{name:'Amazon',tier:'gold',category:'E-commerce'}] } },
  { id:'techkriti',     collegeId:'iitk',     name:'Techkriti',     tagline:"IIT Kanpur's annual technical & entrepreneurship festival",type:'tech',     icon:'⚙️', iconBg:'rgba(67,232,192,0.12)',   footfall:'40,000+',   sponsors_count:28, years:{ '2024':[{name:'Google',tier:'title',category:'Technology'},{name:'Microsoft',tier:'gold',category:'Technology'},{name:'Qualcomm',tier:'gold',category:'Semiconductors'},{name:'Goldman Sachs',tier:'silver',category:'Finance'}],'2023':[{name:'Amazon',tier:'title',category:'Technology'},{name:'Adobe',tier:'gold',category:'Software'},{name:'Razorpay',tier:'silver',category:'Fintech'}] } },
  { id:'tarang',        collegeId:'lsr',      name:'Tarang',        tagline:"LSR's celebrated annual cultural festival",               type:'cultural', icon:'🎭', iconBg:'rgba(255,101,132,0.15)',  footfall:'12,000+',   sponsors_count:16, years:{ '2024':[{name:'Nykaa',tier:'title',category:'Beauty'},{name:'Myntra',tier:'gold',category:'Fashion'},{name:'Spotify',tier:'gold',category:'Music Streaming'},{name:'Zomato',tier:'silver',category:'Food Delivery'},{name:'Bewakoof',tier:'silver',category:'Fashion'},{name:'Mamaearth',tier:'associate',category:'Beauty'}],'2023':[{name:'Nykaa',tier:'title',category:'Beauty'},{name:'Flipkart',tier:'gold',category:'E-commerce'},{name:'boAt',tier:'silver',category:'Electronics'}],'2022':[{name:'Myntra',tier:'title',category:'Fashion'},{name:'Amazon',tier:'gold',category:'E-commerce'},{name:'Pepsi',tier:'silver',category:'Beverages'}],'2021':[{name:'Jio',tier:'title',category:'Telecom'},{name:'Paytm',tier:'gold',category:'Fintech'}] } },
]

const UPCOMING = [
  { date:'Mar 28–30, 2025', fest:'Engifest 2025',   college:'DTU',        collegeId:'dtu',   type:'Cultural + Tech', seeking:true,  tags:['Cultural','Technical','50k+ footfall'] },
  { date:'Apr 4–6, 2025',   fest:'Odyssey 2025',    college:'IIIT Delhi', collegeId:'iiitd', type:'Cultural',        seeking:true,  tags:['Cultural','15k footfall'] },
  { date:'Apr 11–13, 2025', fest:'Ojas 2025',       college:'NSUT',       collegeId:'nsut',  type:'Tech Fest',       seeking:false, tags:['Technical','Hackathon'] },
  { date:'Apr 18–20, 2025', fest:'Crossroads 2025', college:'SRCC',       collegeId:'srcc',  type:'Cultural',        seeking:true,  tags:['Cultural','Commerce'] },
  { date:'May 2–4, 2025',   fest:'Rendezvous 2025', college:'IIT Delhi',  collegeId:'iitd',  type:'Cultural',        seeking:true,  tags:['Cultural','60k+ footfall'] },
  { date:'May 9–11, 2025',  fest:'Tarang 2025',     college:'LSR',        collegeId:'lsr',   type:'Cultural',        seeking:false, tags:['Cultural',"Women's College"] },
]

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI)
    console.log('✅ Connected to MongoDB')

    await collegeModel.deleteMany()
    await festModel.deleteMany()
    await upcomingModel.deleteMany()
    await contactModel.deleteMany()
    console.log('🗑️  Cleared old data')

    await collegeModel.insertMany(COLLEGES)
    console.log(`✅ Inserted ${COLLEGES.length} colleges`)

    await festModel.insertMany(FESTS)
    console.log(`✅ Inserted ${FESTS.length} fests`)

    await upcomingModel.insertMany(UPCOMING)
    console.log(`✅ Inserted ${UPCOMING.length} upcoming events`)

    await contactModel.insertMany(CONTACTS)
    console.log(`✅ Inserted ${CONTACTS.length} contacts`)

    console.log('\n🎉 Database seeded successfully!')
    process.exit(0)
  } catch (err) {
    console.error('❌ Seed error:', err.message)
    process.exit(1)
  }
}

seed()